import type { ColorTheme, FontStyle } from '../components/PersonalizationDialog';

export function getThemeClasses(theme: ColorTheme) {
  const themes = {
    dark: {
      sidebar: 'bg-gray-950 border-gray-800',
      mainBg: 'bg-gray-900',
      header: 'border-gray-800 bg-gray-950',
      title: 'text-white',
      newChatBtn: 'bg-blue-600 hover:bg-blue-700 text-white border-0',
      incognitoBtn: 'bg-gray-700 hover:bg-gray-600 text-white border-0',
      navItem: 'hover:bg-gray-800 text-gray-300',
      separator: 'bg-gray-800',
      chatItem: 'hover:bg-gray-800',
      chatItemActive: 'bg-indigo-900/30',
      chatItemText: 'text-gray-100',
      userMessage: 'bg-blue-600 text-white',
      aiMessage: 'bg-gray-800 text-gray-100',
      userAvatar: 'bg-blue-600',
      aiAvatar: 'bg-green-600',
      inputBorder: 'border border-gray-700 focus-visible:ring-blue-500',
      sendButton: 'bg-blue-600 hover:bg-blue-700',
      outputPanel: 'bg-gray-950 border border-gray-800',
      chatArea: 'bg-gray-900',
    },
    light: {
      sidebar: 'bg-white border-gray-200',
      mainBg: 'bg-gray-50',
      header: 'border-gray-200 bg-white',
      title: 'text-gray-900',
      newChatBtn: 'bg-blue-600 hover:bg-blue-700 text-white border-0',
      incognitoBtn: 'bg-gray-600 hover:bg-gray-700 text-white border-0',
      navItem: 'hover:bg-gray-100 text-gray-700',
      separator: 'bg-gray-200',
      chatItem: 'hover:bg-gray-100',
      chatItemActive: 'bg-indigo-50',
      chatItemText: 'text-gray-900',
      userMessage: 'bg-blue-600 text-white',
      aiMessage: 'bg-white text-gray-900 border border-gray-200',
      userAvatar: 'bg-blue-600',
      aiAvatar: 'bg-green-600',
      inputBorder: 'border border-gray-300 focus-visible:ring-blue-500',
      sendButton: 'bg-blue-600 hover:bg-blue-700',
      outputPanel: 'bg-white border border-gray-200',
      chatArea: 'bg-gray-50',
    },
    minimal: {
      sidebar: 'bg-white border-gray-100',
      mainBg: 'bg-white',
      header: 'border-gray-100 bg-white',
      title: 'text-gray-900',
      newChatBtn: 'bg-gray-900 hover:bg-gray-800 text-white border-0',
      incognitoBtn: 'bg-gray-700 hover:bg-gray-600 text-white border-0',
      navItem: 'hover:bg-gray-50 text-gray-600',
      separator: 'bg-gray-100',
      chatItem: 'hover:bg-gray-50',
      chatItemActive: 'bg-indigo-50',
      chatItemText: 'text-gray-900',
      userMessage: 'bg-gray-900 text-white',
      aiMessage: 'bg-gray-50 text-gray-900',
      userAvatar: 'bg-gray-900',
      aiAvatar: 'bg-gray-700',
      inputBorder: 'border border-gray-200 focus-visible:ring-gray-400',
      sendButton: 'bg-gray-900 hover:bg-gray-800',
      outputPanel: 'bg-white border border-gray-100',
      chatArea: 'bg-white',
    },
    'singapore-red': {
      sidebar: 'bg-gradient-to-br from-red-50 via-white to-red-50 border-red-200',
      mainBg: 'bg-gradient-to-br from-red-50 via-white to-red-50',
      header: 'border-red-200 bg-gradient-to-r from-red-100 to-white',
      title: 'bg-gradient-to-r from-red-700 to-red-600 bg-clip-text text-transparent',
      newChatBtn: 'bg-gradient-to-r from-red-600 to-red-500 hover:from-red-700 hover:to-red-600 text-white border-0',
      incognitoBtn: 'bg-gradient-to-r from-red-700 to-red-600 hover:from-red-800 hover:to-red-700 text-white border-0',
      navItem: 'hover:bg-red-100 text-red-800',
      separator: 'bg-gradient-to-r from-red-300 to-red-200',
      chatItem: 'hover:bg-gradient-to-r hover:from-red-50 hover:to-red-100',
      chatItemActive: 'bg-gradient-to-r from-red-100 to-red-50',
      chatItemText: 'text-red-900',
      userMessage: 'bg-gradient-to-r from-red-600 to-red-500 text-white shadow-md',
      aiMessage: 'bg-white border border-red-200 text-gray-900 shadow-sm',
      userAvatar: 'bg-gradient-to-br from-red-600 to-red-500 shadow-lg',
      aiAvatar: 'bg-gradient-to-br from-red-400 to-red-300 shadow-lg',
      inputBorder: 'border-2 border-red-300 focus-visible:ring-red-500',
      sendButton: 'bg-gradient-to-r from-red-600 to-red-500 hover:from-red-700 hover:to-red-600 shadow-lg',
      outputPanel: 'bg-white border border-red-200',
      chatArea: 'bg-gradient-to-br from-red-50 via-white to-red-50',
    },
    'pastel-pink': {
      sidebar: 'bg-gradient-to-br from-pink-50 via-rose-50 to-pink-100 border-pink-200',
      mainBg: 'bg-gradient-to-br from-pink-50 via-rose-50 to-pink-100',
      header: 'border-pink-200 bg-gradient-to-r from-pink-100 via-rose-100 to-pink-100',
      title: 'bg-gradient-to-r from-pink-600 via-rose-600 to-pink-600 bg-clip-text text-transparent',
      newChatBtn: 'bg-gradient-to-r from-pink-400 to-rose-400 hover:from-pink-500 hover:to-rose-500 text-white border-0',
      incognitoBtn: 'bg-gradient-to-r from-pink-500 to-rose-500 hover:from-pink-600 hover:to-rose-600 text-white border-0',
      navItem: 'hover:bg-pink-100 text-pink-700',
      separator: 'bg-gradient-to-r from-pink-300 via-rose-300 to-pink-300',
      chatItem: 'hover:bg-gradient-to-r hover:from-pink-100 hover:to-rose-100',
      chatItemActive: 'bg-gradient-to-r from-pink-100 to-rose-100',
      chatItemText: 'text-pink-900',
      userMessage: 'bg-gradient-to-r from-pink-400 to-rose-400 text-white shadow-md',
      aiMessage: 'bg-white border border-pink-200 text-gray-900 shadow-sm',
      userAvatar: 'bg-gradient-to-br from-pink-400 to-rose-500 shadow-lg',
      aiAvatar: 'bg-gradient-to-br from-pink-300 to-rose-400 shadow-lg',
      inputBorder: 'border-2 border-pink-300 focus-visible:ring-pink-400',
      sendButton: 'bg-gradient-to-r from-pink-400 to-rose-400 hover:from-pink-500 hover:to-rose-500 shadow-lg',
      outputPanel: 'bg-white border border-pink-200',
      chatArea: 'bg-gradient-to-br from-pink-50 via-rose-50 to-pink-100',
    },
    'army-green': {
      sidebar: 'bg-gradient-to-br from-green-900 via-green-800 to-green-900 border-green-700',
      mainBg: 'bg-gradient-to-br from-green-900 via-green-800 to-green-900',
      header: 'border-green-700 bg-gradient-to-r from-green-900 to-green-800',
      title: 'text-green-100',
      newChatBtn: 'bg-gradient-to-r from-green-700 to-green-600 hover:from-green-800 hover:to-green-700 text-white border-0',
      incognitoBtn: 'bg-gradient-to-r from-green-800 to-green-700 hover:from-green-900 hover:to-green-800 text-white border-0',
      navItem: 'hover:bg-green-800 text-green-200',
      separator: 'bg-green-700',
      chatItem: 'hover:bg-green-800',
      chatItemActive: 'bg-green-800',
      chatItemText: 'text-green-100',
      userMessage: 'bg-gradient-to-r from-green-700 to-green-600 text-white shadow-md',
      aiMessage: 'bg-green-950 border border-green-800 text-green-100 shadow-sm',
      userAvatar: 'bg-gradient-to-br from-green-600 to-green-500 shadow-lg',
      aiAvatar: 'bg-gradient-to-br from-green-700 to-green-600 shadow-lg',
      inputBorder: 'border-2 border-green-700 focus-visible:ring-green-500',
      sendButton: 'bg-gradient-to-r from-green-700 to-green-600 hover:from-green-800 hover:to-green-700 shadow-lg',
      outputPanel: 'bg-green-950 border border-green-800',
      chatArea: 'bg-gradient-to-br from-green-900 via-green-800 to-green-900',
    },
    rainbow: {
      sidebar: 'bg-gradient-to-br from-red-100 via-yellow-100 via-green-100 via-blue-100 to-purple-100 border-purple-300',
      mainBg: 'bg-gradient-to-br from-red-50 via-yellow-50 via-green-50 via-blue-50 to-purple-50',
      header: 'border-purple-300 bg-gradient-to-r from-red-100 via-yellow-100 via-green-100 via-blue-100 to-purple-100',
      title: 'bg-gradient-to-r from-red-600 via-orange-500 via-yellow-500 via-green-500 via-blue-500 to-purple-600 bg-clip-text text-transparent',
      newChatBtn: 'bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 to-purple-500 hover:from-red-600 hover:via-yellow-600 hover:via-green-600 hover:via-blue-600 hover:to-purple-600 text-white border-0',
      incognitoBtn: 'bg-gradient-to-r from-purple-500 via-blue-500 to-indigo-500 hover:from-purple-600 hover:via-blue-600 hover:to-indigo-600 text-white border-0',
      navItem: 'hover:bg-gradient-to-r hover:from-red-100 hover:via-yellow-100 hover:to-green-100 text-purple-700',
      separator: 'bg-gradient-to-r from-red-300 via-yellow-300 via-green-300 via-blue-300 to-purple-300',
      chatItem: 'hover:bg-gradient-to-r hover:from-red-100 hover:via-yellow-100 hover:to-purple-100',
      chatItemActive: 'bg-gradient-to-r from-red-100 via-yellow-100 to-purple-100',
      chatItemText: 'text-purple-900',
      userMessage: 'bg-gradient-to-r from-red-500 via-orange-500 via-yellow-500 to-green-500 text-white shadow-md',
      aiMessage: 'bg-gradient-to-r from-blue-100 via-purple-100 to-pink-100 border border-purple-200 text-gray-900 shadow-md',
      userAvatar: 'bg-gradient-to-br from-red-500 via-orange-500 to-yellow-500 shadow-lg',
      aiAvatar: 'bg-gradient-to-br from-blue-500 via-purple-500 to-pink-500 shadow-lg',
      inputBorder: 'border-2 border-purple-300 focus-visible:ring-purple-500',
      sendButton: 'bg-gradient-to-r from-red-500 via-yellow-500 via-green-500 via-blue-500 to-purple-500 hover:from-red-600 hover:to-purple-600 shadow-lg',
      outputPanel: 'bg-white border border-purple-200',
      chatArea: 'bg-gradient-to-br from-red-50 via-yellow-50 via-green-50 via-blue-50 to-purple-50',
    },
    'national-day': {
      sidebar: 'bg-gradient-to-br from-red-600 via-red-500 to-white border-red-400',
      mainBg: 'bg-gradient-to-br from-red-500 via-white to-red-500',
      header: 'border-red-400 bg-gradient-to-r from-red-600 via-white to-red-600',
      title: 'bg-gradient-to-r from-red-700 via-yellow-500 to-red-700 bg-clip-text text-transparent',
      newChatBtn: 'bg-gradient-to-r from-red-600 via-yellow-400 to-red-600 hover:from-red-700 hover:via-yellow-500 hover:to-red-700 text-white border-2 border-yellow-400',
      incognitoBtn: 'bg-gradient-to-r from-red-700 via-red-600 to-red-700 hover:from-red-800 hover:to-red-800 text-white border-2 border-white',
      navItem: 'hover:bg-red-100 text-red-900',
      separator: 'bg-gradient-to-r from-red-400 via-yellow-300 to-red-400 h-1',
      chatItem: 'hover:bg-gradient-to-r hover:from-red-50 hover:via-yellow-50 hover:to-red-50',
      chatItemActive: 'bg-gradient-to-r from-red-100 via-yellow-50 to-red-100 border-l-4 border-red-600',
      chatItemText: 'text-red-900',
      userMessage: 'bg-gradient-to-r from-red-600 via-red-500 to-red-600 text-white shadow-lg border-2 border-yellow-400',
      aiMessage: 'bg-white border-2 border-red-400 text-gray-900 shadow-lg',
      userAvatar: 'bg-gradient-to-br from-red-600 via-yellow-500 to-red-600 shadow-lg border-2 border-white',
      aiAvatar: 'bg-gradient-to-br from-white via-red-200 to-white shadow-lg border-2 border-red-600',
      inputBorder: 'border-2 border-red-400 focus-visible:ring-red-500 focus-visible:ring-offset-2',
      sendButton: 'bg-gradient-to-r from-red-600 via-yellow-400 to-red-600 hover:from-red-700 hover:via-yellow-500 hover:to-red-700 shadow-lg border-2 border-yellow-500',
      outputPanel: 'bg-gradient-to-br from-white via-red-50 to-white border-2 border-red-400',
      chatArea: 'bg-gradient-to-br from-red-100 via-white via-yellow-50 to-red-100',
    },
  };

  return themes[theme];
}

export function getFontClasses(fontStyle: FontStyle) {
  const fonts = {
    modern: {
      base: '',
      title: '',
      message: '',
      input: '',
    },
    seniors: {
      base: 'text-lg',
      title: 'text-2xl',
      message: 'text-xl',
      input: 'text-lg',
    },
    compact: {
      base: 'text-sm',
      title: 'text-base',
      message: 'text-sm',
      input: 'text-sm',
    },
  };

  return fonts[fontStyle];
}